# üöÄ Python List Practice Notebook
This notebook contains **10 just-above-beginner Python list challenges**.

Try solving each problem by writing Python code in the cells below. üí°

---

## 1Ô∏è‚É£ Remove Duplicates & Sort

In [2]:
numbers = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
# Your code here
n=[]

for i in numbers:
  if i not in n:
    n.append(i)

print(n)

[3, 1, 4, 5, 9, 2, 6]

## 2Ô∏è‚É£ Find Second Largest Number

In [6]:
nums = [10, 20, 4, 45, 98, 99, 5]
# Your code here
n=len(nums)
for i in range(n):
  if i==2:
    break
  for j in range(n-i-1):
    if nums[j]>nums[j+1]:
      temp=nums[j]
      nums[j]=nums[j+1]
      nums[j+1]=temp

print(nums[-2])

98

In [14]:

nums = [10, 20, 4, 45, 98, 99, 5]
first=nums[1]
second=nums[0]
for i in range(2,len(nums)):
  if nums[i]>first:
    temp=first
    first=nums[i]
    second=temp

print(f'first: {first}')
print(f'second: {second}')

first: 99
second: 98

## 3Ô∏è‚É£ Rotate List Right by K

In [ ]:
nums = [1, 2, 3, 4, 5]
k = 2
# Your code here
#nums = [4,5,1,2,3]

## 4Ô∏è‚É£ Merge Two Sorted Lists

In [18]:
list1 = [1, 3, 5, 7]
list2 = [2, 4, 6, 8]
newlist = []

n1 = len(list1)
n2 = len(list2)

# Your code here
list=list1+list2
print(list)

[1, 3, 5, 7, 2, 4, 6, 8]

In [30]:
list1 = [1, 3, 5, 7]
list2 = [2, 4, 6, 8]

newlist = []

n1 = len(list1)
n2 = len(list2)

m=0
n=0

while(m<n1 and n<n2):
  if list1[m] < list2[n]:
    newlist.append(list1[m])
    m+=1
  else:
    newlist.append(list2[n])
    n+=1

while(m < n1):
  newlist.append(list1[m])
  m+=1

while(n < n2):
  newlist.append(list2[n])
  n+=1

print(newlist)

[1, 2, 3, 4, 5, 6, 7, 8]

## 5Ô∏è‚É£ Find All Pairs That Sum to K

In [11]:
nums = [1, 2, 3, 4, 5, 6, 7, 8]
k = 9
l=[]
s=set()

for i in nums:
  n = k-i
  if n in s:
    l.append((n,i))

  s.add(i)
print(l)
print(s)

[(4, 5), (3, 6), (2, 7), (1, 8)]
{1, 2, 3, 4, 5, 6, 7, 8}

## 6Ô∏è‚É£ Flatten a Nested List

In [ ]:
nested = [[1, 2, [3]], 4, [5, 6], [[7, 8]]]
# Your code here

## 7Ô∏è‚É£ Find Missing Number in a Consecutive List

In [10]:
nums = [11, 12, 13, 15,16, 17, 18]
# Your code here
j=nums[0]
n=nums[-1]

while j<n:
  if j not in nums:
    print(j)
    break
  else:
    j+=1

14

## 8Ô∏è‚É£ Move All Zeroes to End

In [16]:
nums = [0, 1, 0, 3, 12, 0, 5]
# Your code here
l=[]
l1=[]

for i in nums:
  if i ==0:
    l.append(i)
  else:
    l1.append(i)

l1.extend(l)
print(l1)

[1, 3, 12, 5, 0, 0, 0]

## 9Ô∏è‚É£ Find Most Frequent Element

In [27]:
nums = [1, 3, 1, 3, 2, 1, 4, 1, 5, 1]
# Your code here
d={}

for i in nums:
  d[i]=d.get(i,0)+1
print(d)

maximum=max(d, key=d.get)
print(maximum)

{1: 5, 3: 2, 2: 1, 4: 1, 5: 1}
1

## üîü Remove Elements That Appear More Than Once

In [29]:
nums = [4, 5, 6, 7, 5, 6, 8, 9]
# Your code here
l=[]

for i in nums:
  if i not in l:
    l.append(i)
print(l)

[4, 5, 6, 7, 8, 9]